import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn, Almarai } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazirmatn = Vazirmatn({
  subsets: ['arabic'],
  variable: '--font-vazirmatn',
});

const almarai = Almarai({
      weight: ['300', '400', '700', '800'],
      subsets: ['arabic'],
      variable: '--font-almarai',
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazirmatn.variable} ${almarai.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
